export default {
  timeTable: [
    {
      id: "bd7acbea-c1b1-46c2-aed5-3ad53abb28ba",
      title: "Artificial Intelligence",
      startTime: "11:30 AM",
      endTime: "1:00 PM",
      teacher: "Dr. Sohail Yousaf",
      location: "R1 (New-Block)",
      isReschedule: false,
    },
    {
      id: "3ac68afc-c605-48d3-a4f8-fbd91aa97f63",
      title: "Intro To Information Security",
      startTime: "11:30 AM",
      endTime: "1:00 PM",
      teacher: "Sir, Mujtabah",
      location: "R1 (New-Block)",
      isReschedule: true,
    },
    {
      id: "58694a0f-3da1-471f-bd96-145571e29d72",
      title: "Ethical & Legal Issue",
      startTime: "11:30 AM",
      endTime: "1:00 PM",
      teacher: "Sir, Ismat Ullah",
      location: "R1 (New-Block)",
      isReschedule: false,
    },
  ],
  weekly: [
    {
      id: "bd7acbea-c1b1-46c2-aed5-3ad53abb2332",
      title: "Monday",
      timeTable: [
        {
          id: "bd7acbea-c1b1-46c2-aed5-3ad53abb28ba",
          title: "Artificial Intelligence",
          startTime: "11:30 AM",
          endTime: "1:00 PM",
          teacher: "Dr. Sohail Yousaf",
          location: "R1 (New-Block)",
          isReschedule: false,
        },
        {
          id: "3ac68afc-c605-48d3-a4f8-fbd91aa97f63",
          title: "Intro To Information Security",
          startTime: "11:30 AM",
          endTime: "1:00 PM",
          teacher: "Sir, Mujtabah",
          location: "R1 (New-Block)",
          isReschedule: true,
        },
        {
          id: "58694a0f-3da1-471f-bd96-145571e29d72",
          title: "Ethical & Legal Issue",
          startTime: "11:30 AM",
          endTime: "1:00 PM",
          teacher: "Sir, Ismat Ullah",
          location: "R1 (New-Block)",
          isReschedule: false,
        },
      ],
    },
    {
      id: "ca7acbea-c1b1-46c2-aed5-3ad53abb2332",
      title: "Tuesday",
      timeTable: [
        {
          id: "bd7acbea-c11-46c2-aed5-3ad53abb28ba",
          title: "Artificial Intelligence",
          startTime: "11:30 AM",
          endTime: "1:00 PM",
          teacher: "Dr. Sohail Yousaf",
          location: "R1 (New-Block)",
          isReschedule: false,
        },
        {
          id: "3ac68afc-c655-48d3-a4f8-fbd91aa97f63",
          title: "Intro To Information Security",
          startTime: "11:30 AM",
          endTime: "1:00 PM",
          teacher: "Sir, Mujtabah",
          location: "R1 (New-Block)",
          isReschedule: true,
        },
        {
          id: "58694a0f-3d61-471f-bd96-145571e29d72",
          title: "Ethical & Legal Issue",
          startTime: "11:30 AM",
          endTime: "1:00 PM",
          teacher: "Sir, Ismat Ullah",
          location: "R1 (New-Block)",
          isReschedule: false,
        },
      ],
    },
    {
      id: "ea7acbea-c1b1-46c2-aed5-3ad53abb2332",
      title: "Wednesday",
      timeTable: [
        {
          id: "bd7acbea-c11-46c2-aed5-3ad53abb28ba",
          title: "Artificial Intelligence",
          startTime: "11:30 AM",
          endTime: "1:00 PM",
          teacher: "Dr. Sohail Yousaf",
          location: "R1 (New-Block)",
          isReschedule: false,
        },
        {
          id: "3ac68afc-c655-48d3-a4f8-fbd91aa97f63",
          title: "Intro To Information Security",
          startTime: "11:30 AM",
          endTime: "1:00 PM",
          teacher: "Sir, Mujtabah",
          location: "R1 (New-Block)",
          isReschedule: true,
        },
        {
          id: "58694a0f-3d61-471f-bd96-145571e29d72",
          title: "Ethical & Legal Issue",
          startTime: "11:30 AM",
          endTime: "1:00 PM",
          teacher: "Sir, Ismat Ullah",
          location: "R1 (New-Block)",
          isReschedule: false,
        },
      ],
    },
    {
      id: "qa733bea-c1b1-46c2-aed5-3ad53abb2332",
      title: "Thursday",
      timeTable: [
        {
          id: "bd7acbea-c11-46c2-aed5-3ad53abb28ba",
          title: "Artificial Intelligence",
          startTime: "11:30 AM",
          endTime: "1:00 PM",
          teacher: "Dr. Sohail Yousaf",
          location: "R1 (New-Block)",
          isReschedule: false,
        },
        {
          id: "3ac68afc-c655-48d3-a4f8-fbd91aa97f63",
          title: "Intro To Information Security",
          startTime: "11:30 AM",
          endTime: "1:00 PM",
          teacher: "Sir, Mujtabah",
          location: "R1 (New-Block)",
          isReschedule: true,
        },
        {
          id: "58694a0f-3d61-471f-bd96-145571e29d72",
          title: "Ethical & Legal Issue",
          startTime: "11:30 AM",
          endTime: "1:00 PM",
          teacher: "Sir, Ismat Ullah",
          location: "R1 (New-Block)",
          isReschedule: false,
        },
      ],
    },
    {
      id: "ja7a3bea-c1b1-46c2-aed5-3ad53abb2332",
      title: "Friday",
      timeTable: [
        {
          id: "bd7acbea-c11-46c2-aed5-3ad53abb28ba",
          title: "Artificial Intelligence",
          startTime: "11:30 AM",
          endTime: "1:00 PM",
          teacher: "Dr. Sohail Yousaf",
          location: "R1 (New-Block)",
          isReschedule: false,
        },
        {
          id: "3ac68afc-c655-48d3-a4f8-fbd91aa97f63",
          title: "Intro To Information Security",
          startTime: "11:30 AM",
          endTime: "1:00 PM",
          teacher: "Sir, Mujtabah",
          location: "R1 (New-Block)",
          isReschedule: true,
        },
        {
          id: "58694a0f-3d61-471f-bd96-145571e29d72",
          title: "Ethical & Legal Issue",
          startTime: "11:30 AM",
          endTime: "1:00 PM",
          teacher: "Sir, Ismat Ullah",
          location: "R1 (New-Block)",
          isReschedule: false,
        },
      ],
    },
  ],
};
