export default {
  timeTable: [
    {
      id: "bd7acbea-c1b1-46c2-aed5-3ad53abb28ba",
      title: "Artificial Intelligence",
      startTime: "11:30 AM",
      endTime: "1:00 PM",
      teacher: "Dr. Sohail Yousaf",
      location: "R1 (New-Block)",
      isReschedule: false,
    },
    {
      id: "3ac68afc-c605-48d3-a4f8-fbd91aa97f63",
      title: "Intro To Information Security",
      startTime: "11:30 AM",
      endTime: "1:00 PM",
      teacher: "Sir, Mujtabah",
      location: "R1 (New-Block)",
      isReschedule: true,
    },
    {
      id: "58694a0f-3da1-471f-bd96-145571e29d72",
      title: "Ethical & Legal Issue",
      startTime: "11:30 AM",
      endTime: "1:00 PM",
      teacher: "Sir, Ismat Ullah",
      location: "R1 (New-Block)",
      isReschedule: false,
    },
  ],
  weekly: [
    {
      id: "bd7acbea-c1b1-46c2-aed5-3ad53abb2332",
      title: "Monday",
      timeTable: [
        {
          id: "bd7acbea-c1b1-46c2-aed5-3ad53abb28ba",
          title: "Artificial Intelligence",
          startTime: "11:30 AM",
          endTime: "1:00 PM",
          teacher: "Dr. Sohail Yousaf",
          location: "R1 (New-Block)",
          isReschedule: false,
        },
        {
          id: "3ac68afc-c605-48d3-a4f8-fbd91aa97f63",
          title: "Intro To Information Security",
          startTime: "11:30 AM",
          endTime: "1:00 PM",
          teacher: "Sir, Mujtabah",
          location: "R1 (New-Block)",
          isReschedule: true,
        },
        {
          id: "58694a0f-3da1-471f-bd96-145571e29d72",
          title: "Ethical & Legal Issue",
          startTime: "11:30 AM",
          endTime: "1:00 PM",
          teacher: "Sir, Ismat Ullah",
          location: "R1 (New-Block)",
          isReschedule: false,
        },
      ],
    },
    {
      id: "ca7acbea-c1b1-46c2-aed5-3ad53abb2332",
      title: "Tuesday",
      timeTable: [
        {
          id: "bd7acbea-c11-46c2-aed5-3ad53abb28ba",
          title: "Artificial Intelligence",
          startTime: "11:30 AM",
          endTime: "1:00 PM",
          teacher: "Dr. Sohail Yousaf",
          location: "R1 (New-Block)",
          isReschedule: false,
        },
        {
          id: "3ac68afc-c655-48d3-a4f8-fbd91aa97f63",
          title: "Intro To Information Security",
          startTime: "11:30 AM",
          endTime: "1:00 PM",
          teacher: "Sir, Mujtabah",
          location: "R1 (New-Block)",
          isReschedule: true,
        },
        {
          id: "58694a0f-3d61-471f-bd96-145571e29d72",
          title: "Ethical & Legal Issue",
          startTime: "11:30 AM",
          endTime: "1:00 PM",
          teacher: "Sir, Ismat Ullah",
          location: "R1 (New-Block)",
          isReschedule: false,
        },
      ],
    },
    {
      id: "ea7acbea-c1b1-46c2-aed5-3ad53abb2332",
      title: "Wednesday",
      timeTable: [
        {
          id: "bd7acbea-c11-46c2-aed5-3ad53abb28ba",
          title: "Artificial Intelligence",
          startTime: "11:30 AM",
          endTime: "1:00 PM",
          teacher: "Dr. Sohail Yousaf",
          location: "R1 (New-Block)",
          isReschedule: false,
        },
        {
          id: "3ac68afc-c655-48d3-a4f8-fbd91aa97f63",
          title: "Intro To Information Security",
          startTime: "11:30 AM",
          endTime: "1:00 PM",
          teacher: "Sir, Mujtabah",
          location: "R1 (New-Block)",
          isReschedule: true,
        },
        {
          id: "58694a0f-3d61-471f-bd96-145571e29d72",
          title: "Ethical & Legal Issue",
          startTime: "11:30 AM",
          endTime: "1:00 PM",
          teacher: "Sir, Ismat Ullah",
          location: "R1 (New-Block)",
          isReschedule: false,
        },
      ],
    },
    {
      id: "qa733bea-c1b1-46c2-aed5-3ad53abb2332",
      title: "Thursday",
      timeTable: [
        {
          id: "bd7acbea-c11-46c2-aed5-3ad53abb28ba",
          title: "Artificial Intelligence",
          startTime: "11:30 AM",
          endTime: "1:00 PM",
          teacher: "Dr. Sohail Yousaf",
          location: "R1 (New-Block)",
          isReschedule: false,
        },
        {
          id: "3ac68afc-c655-48d3-a4f8-fbd91aa97f63",
          title: "Intro To Information Security",
          startTime: "11:30 AM",
          endTime: "1:00 PM",
          teacher: "Sir, Mujtabah",
          location: "R1 (New-Block)",
          isReschedule: true,
        },
        {
          id: "58694a0f-3d61-471f-bd96-145571e29d72",
          title: "Ethical & Legal Issue",
          startTime: "11:30 AM",
          endTime: "1:00 PM",
          teacher: "Sir, Ismat Ullah",
          location: "R1 (New-Block)",
          isReschedule: false,
        },
      ],
    },
    {
      id: "ja7a3bea-c1b1-46c2-aed5-3ad53abb2332",
      title: "Friday",
      timeTable: [
        {
          id: "bd7acbea-c11-46c2-aed5-3ad53abb28ba",
          title: "Artificial Intelligence",
          startTime: "11:30 AM",
          endTime: "1:00 PM",
          teacher: "Dr. Sohail Yousaf",
          location: "R1 (New-Block)",
          isReschedule: false,
        },
        {
          id: "3ac68afc-c655-48d3-a4f8-fbd91aa97f63",
          title: "Intro To Information Security",
          startTime: "11:30 AM",
          endTime: "1:00 PM",
          teacher: "Sir, Mujtabah",
          location: "R1 (New-Block)",
          isReschedule: true,
        },
        {
          id: "58694a0f-3d61-471f-bd96-145571e29d72",
          title: "Ethical & Legal Issue",
          startTime: "11:30 AM",
          endTime: "1:00 PM",
          teacher: "Sir, Ismat Ullah",
          location: "R1 (New-Block)",
          isReschedule: false,
        },
      ],
    },
  ],
  teacher: {
    timeTable: [
      {
        id: "bd7acbea-c1b1-46c2-aed5-3ad53abb28ba",
        title: "Artificial Intelligence",
        semester: "8th",
        section: "B",
        startTime: "11:30 AM",
        endTime: "1:00 PM",
        location: "R1 (New-Block)",
        isReschedule: false,
      },
      {
        id: "3ac68afc-c605-48d3-a4f8-fbd91aa97f63",
        title: "Artificial Intelligence",
        semester: "8th",
        section: "A",
        startTime: "11:30 AM",
        endTime: "1:00 PM",
        location: "R1 (New-Block)",
        isReschedule: false,
      },
      {
        id: "58694a0f-3da1-471f-bd96-145571e29d72",
        title: "Ethical & Legal Issue",
        semester: "7th",
        section: "A",
        startTime: "11:30 AM",
        endTime: "1:00 PM",
        location: "R1 (New-Block)",
        isReschedule: false,
      },
      {
        id: "58694a0f-3da1-4733f-bd96-145571e29d72",
        title: "Ethical & Legal Issue",
        semester: "7th",
        section: "B",
        startTime: "11:30 AM",
        endTime: "1:00 PM",
        location: "R1 (New-Block)",
        isReschedule: false,
      },
    ],
    weekly: [
      {
        id: "bd7ac3bea-c1b1-46c2-aed5-3ad53abb2332",
        title: "Monday",
        timeTable: [
          {
            id: "bd74cbea-c1b1-46c2-aed5-3ad53abb28ba",
            title: "Artificial Intelligence",
            semester: "8th",
            section: "B",
            startTime: "11:30 AM",
            endTime: "1:00 PM",
            location: "R1 (New-Block)",
            isReschedule: false,
          },
          {
            id: "bd7ac5ea-c1b1-46c2-aed5-3ad53abb28ba",
            title: "Artificial Intelligence",
            semester: "8th",
            section: "A",
            startTime: "11:30 AM",
            endTime: "1:00 PM",
            location: "R1 (New-Block)",
            isReschedule: false,
          },
        ],
      },
      {
        id: "ca7agbea-c1b1-46c2-aed5-3ad53abb2332",
        title: "Tuesday",
        timeTable: [],
      },
      {
        id: "ea7acvea-c1b1-46c2-aed5-3ad53abb2332",
        title: "Wednesday",
        timeTable: [
          {
            id: "3ac68bbc-c655-48d3-a4f8-fbd91aa97f63",
            title: "Intro To Information Security",
            semester: "6th",
            section: "A",
            startTime: "11:30 AM",
            endTime: "1:00 PM",
            location: "R1 (New-Block)",
            isReschedule: false,
          },
          {
            id: "3ac6cvafc-c655-48d3-a4f8-fbd91aa97f63",
            title: "Intro To Information Security",
            semester: "6th",
            section: "B",
            startTime: "11:30 AM",
            endTime: "1:00 PM",
            location: "R1 (New-Block)",
            isReschedule: false,
          },
        ],
      },
      {
        id: "qa733acea-c1b1-46c2-aed5-3ad53abb2332",
        title: "Thursday",
        timeTable: [
          {
            id: "bd7accbea-c1b1-46c2-aed5-3ad53abb28ba",
            title: "Artificial Intelligence",
            semester: "8th",
            section: "A",
            startTime: "11:30 AM",
            endTime: "1:00 PM",
            location: "R1 (New-Block)",
            isReschedule: false,
          },
        ],
      },
      {
        id: "ja7a3bcxa-c1b1-46c2-aed5-3ad53abb2332",
        title: "Friday",
        timeTable: [
          {
            id: "bd7acca-c1b1-46c2-aed5-3ad53abb28ba",
            title: "Artificial Intelligence",
            semester: "8th",
            section: "B",
            startTime: "11:30 AM",
            endTime: "1:00 PM",
            location: "R1 (New-Block)",
            isReschedule: false,
          },
        ],
      },
    ],
  },
  subjects: [
    { label: "Artificial Intelligence", value: "Artificial Intelligence" },
    {
      label: "Intro To Information Security",
      value: "Intro To Information Security",
    },
    { label: "Ethical & Legal Issue", value: "Ethical & Legal Issue" },
  ],
  sections: [
    { label: "A", value: "A" },
    { label: "B", value: "B" },
    { label: "C", value: "C" },
    { label: "D", value: "D" },
    { label: "E", value: "E" },
  ],
  semesters: [
    { label: "21", value: "21" },
    { label: "20", value: "20" },
    { label: "19", value: "19" },
    { label: "18", value: "18" },
    { label: "17", value: "17" },
    { label: "16", value: "16" },
  ],
};
